string Xingamento = ("-----");
Console.WriteLine("Me diga o que você pensa sobre quem faz racismo: ");
string FraseEducada = Console.ReadLine()
    .Replace("chato", Xingamento)
    .Replace("chata", Xingamento)
    .Replace("bobo", Xingamento)
    .Replace("boba", Xingamento)
    .Replace("feio", Xingamento)
    .Replace("feia", Xingamento)
    .Replace("boboca", Xingamento)
    .Replace("bocó", Xingamento)
    .Replace("tonto", Xingamento)
    .Replace("tonta", Xingamento)
    .Replace("palerma", Xingamento)
    .Replace("paspalho", Xingamento)
    .Replace("paspalha", Xingamento)
    .Replace("tantã", Xingamento)
    .Replace("panaca", Xingamento)
    .Replace("pentelho", Xingamento)
    .Replace("pentelha", Xingamento)
    .Replace("burro", Xingamento)
    .Replace("burra", Xingamento)
    .Replace("besta", Xingamento)
    .Replace("CHATO", Xingamento)
    .Replace("CHATA", Xingamento)
    .Replace("BOBO", Xingamento)
    .Replace("BOBA", Xingamento)
    .Replace("FEIO", Xingamento)
    .Replace("FEIA", Xingamento)
    .Replace("BOBOCA", Xingamento)
    .Replace("BOCÓ", Xingamento)
    .Replace("TONTO", Xingamento)
    .Replace("TONTA", Xingamento)
    .Replace("PALERMA", Xingamento)
    .Replace("PASPALHO", Xingamento)
    .Replace("PASPALHA", Xingamento)
    .Replace("TANTÃ", Xingamento)
    .Replace("PANACA", Xingamento)
    .Replace("PENTELHO", Xingamento)
    .Replace("PENTELHA", Xingamento)
    .Replace("BURRO", Xingamento)
    .Replace("BURRA", Xingamento)
    .Replace("BESTA", Xingamento);
    Console.WriteLine($"Como eu sou uma criança educada essa pessoa é: {FraseEducada}");